/*
 * VerificaAssinaturaMacros.h
 *
 *  Created on: Mar 15, 2026
 *      Author: marcus
 */

#ifndef TEST_PACKAGE_SRC_UNITTESTS_INCLUDE_VERIFICAASSINATURAMACROS_H_
#define TEST_PACKAGE_SRC_UNITTESTS_INCLUDE_VERIFICAASSINATURAMACROS_H_

#define PKCS12_FILE_PATH "certificado_teste_hub.pfx"
#define AES_KEY "b90XmFVR51L485rxXXCRhupVxva0yDFh"
#define AES_INITIALIZATION_VECTOR "NSVmgGXSm2jRTiyq"
#define PKCS12_ENVVAR_PASSWORD "PKCS12_ENVVAR_PASSWORD"
#define SIGNATURE_FILE_PATH "signature.p7s"
#define MESSAGE_DIGEST_ALGORITHM "sha256"


#endif /* TEST_PACKAGE_SRC_UNITTESTS_INCLUDE_VERIFICAASSINATURAMACROS_H_ */
